
jwt:
  secret-key: abcdefghijklmnopqrstuvwxyz0123456789
  token:
    expired-time-ms: 1800000



spring:
  datasource:
    url: jdbc:mysql://10.10.10.10/web
    username: test
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true



logging:
  level:
    org.springframework.security: DEBUG

